// Export all models
export * from './activity-log.model';
export * from './appointment.model';
export * from './consultation.model';
export * from './dispensation.model';
export * from './doctor.model';
export * from './document.model';
export * from './facility.model';
export * from './inventory.model';
export * from './lab.model';
export * from './notification.model';
export * from './patient.model';
export * from './patient-allergy.model';
export * from './patient-condition.model';
export * from './payment.model';
export * from './prescription.model';
export * from './tenant.model';
export * from './user.model';
export * from './vitals.model';